---
- name: schedule cron job for backup log
  hosts: all
  become: true
  
  tasks:
    - name: copy backup script
      copy:
        src: backup.sh.j2
        dest: /usr/local/bin/backup_{{ env_name }}.sh
        mode: '0755'

    - name: Create cron job for backup
      ansible.builtin.cron:      
        name: "backup script for {{ env_name }}"
        job: "/usr/local/bin/backup_{{ env_name }}.sh"
        minute: "{{ cron_time.split() [0] }}"
        hour: "{{ cron_time.split() [1] }}"
        user: "{{ ansible_user }}"
        state: present    
          
    - name: Debug variables
      debug:
        msg: "env_name={{ env_name }}, cron_time={{ cron_time }}"        
...
