---
- name: installing apache
  hosts: webservers
  become: true

  tasks:
    - name: installing the apache
      apt:
        name: apache2
        state: present

    - name: start the apache
      service:
        name: apache2
        state: started
        enabled: true
      register: apache_status

    - name: status
      debug:
        msg: "apache status is {{apache_status}}"
...