- name: install and configure SSL cert 
  hosts: all
  become: yes
  vars_files:
    - var.yml

  tasks:
    - name: install Certbot, nginx, and dependencies
      apt:
        name: 
          - nginx
          - certbot
          - python3-certbot-nginx
        state: present
        update_cache: yes

    - name : obtain SSL certs
      command: > 
        certbot --nginx -n --agree-tos --email {{ email }} -d {{ domain_name }}

      args:
        creates : "/etc/letsencrypt/live/{{ domain_name }}/fullchain.pem"

    - name: reload nginx
      service:
        name: nginx
        state: restart

    
